import './globals.css'
import { Inter } from 'next/font/google'
import 'css/twemoji.css'
import { MAIN_CONTENT_MIN_HEIGHT } from 'constant'
import { Footer } from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="mx-auto max-w-3xl px-3 sm:px-6 xl:max-w-5xl xl:px-0 bg-white text-black antialiased ">
        <div className="flex flex-col justify-between">
          <main style={{ minHeight: MAIN_CONTENT_MIN_HEIGHT }}>{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  )
}
